### ISSUE TITLE
/wallet command

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/rapydbot#1]

**Comment by netpoe** [comment]
## Acceptance Critera

- [ ] A user can call the `/wallet create` command and a default reply should be sent back in the corresponding language
- [ ] When a user executes `/wallet create` for the 1st time, the Bot should create a Rapyd e-wallet for the user and link it to the user's Telegram id
- [ ] If the user already has a Rapyd e-wallet, reply with the `/wallet balance` response
- [ ] Unit tests for the `wallet` microservice
- [ ] Create a `wallet` microservice
- [ ]

## Wallet microservice

The
