### ISSUE TITLE
/send command

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/rapydbot#2]

**Comment by netpoe** [comment]
## Acceptance Criteria

- [ ] A user can call `/send` | `/transfer` | `/pay` with no command options and get a default reply 
- [ ] A user can call `/send @username` and the bot should reply with whether an `amount reply` OR a `insufficient wallet balance` reply OR `username has no e-wallet` reply
- [ ] A user can call `/send @username <amount>` and if the sender's wallet has a valid balance, perform the transaction using the Rapyd API
- [ ] *Now that I think of it, `/pay` can be another command that sends money from the Rapyd e-wallet to a bank account

Should this command be handled by the `wallet` microservice? The transactions and the wallet history are stored in Rapyd anyways...
