### ISSUE TITLE
/request command

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/rapydbot#3]

**Comment by netpoe** [comment]
## Acceptance Criteria

- [ ] A user can call `/request` and the bot replies with a default response requesting the `username` of the requestee
- [ ] A user can call `/request @username` and the bot sends a checkout page to the corresponding user. The requestee should already have a Rapyd e-wallet, otherwise the bot replies with a `username does not have a Rapyd e-wallet yet` message
- [ ] Requesting is handled by the `wallet` mcs?
- [ ] A user can call `/request @username <amount>` and sends a checkout page URL with the amount to the requestee. The bot replies back with a "request sent!" message
